[build]
  publish = "public"
  command = "hugo"

[context.production.environment]
  HUGO_BASEURL = "https://jaymutuku.netlify.app/"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "hugo --gc -b $DEPLOY_PRIME_URL"  

[context.deploy-preview.environment]
   HUGO_VERSION = "0.75.1"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=600"

[[headers]]
  for = "*.(css|js|woff|woff2|ttf|png|jpg|jpeg)"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404